add max surge in default node pool block
hmcts/aks-module-kubernetes pull request #105
Opened 2024-04-25 15:00 UTC by NickAzureDevops

### Jira link (if applicable)

add max surge under default node pool 

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-04-25 15:01 UTC, thomast1906 requested changes
I am missing context, whats this for/needed etc?

2024-04-25 15:04 UTC, NickAzureDevops commented
> I am missing context, whats this for/needed etc?

it is to fix the max surge issue on the plan there was not defined which will output null 

see here https://dev.azure.com/hmcts/PlatformOperations/_build/results?buildId=565857&view=logs&j=39bcd506-c0f2-5303-b215-cd7204d79260&t=c0e59b66-063d-5b10-5664-b621bb49a864 @thomast1906

2024-04-25 15:17 UTC, danielwilsonkainos commented
@thomast1906 The pipeline is trying to null the max surge value on the system nodepool for clusters. As this is a required value Azure is defaulting it back to 10% and so its cycling a change each time the TF is planned/applied.

The max surge value allows requesting extra quote during the upgrade process. [Docs here](https://learn.microsoft.com/en-us/azure/aks/upgrade-cluster#optimize-upgrades-to-improve-performance-and-minimize-disruptions) Additional nodepools are all set to 33% and its the microsoft recommended value so we've applied the same to the system nodepool which will stop the cyclical change occuring

2024-04-25 15:22 UTC, danielwilsonkainos approved these changes

2024-04-26 09:04 UTC, thomast1906 approved these changes

2024-04-26 09:09 UTC, merged